defaults:
  - _self_
  
# Model configuration
model:
  in_channels: 3
  out_channels: 3  # Output same as input for diffusion
  base_channels: 256
  depth: 5
  time_emb_dim: 64

# Diffusion process configuration
diffusion:
  num_timesteps: 200
  beta_start: 1e-4
  beta_end: 0.02

# Training configuration
training:
  epochs: 30
  batch_size: 16
  seed: 114

# Optimizer configuration
optimizer:
  lr: 1e-4
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0

# Data configuration
data:
  root_dir: "/mnt/users/potato/Ame-Furi/data/5flower"
  image_size: 256
  num_workers: 8
  num_classes: 5

# Logging configuration
logging:
  log_dir: "logs"
  save_dir: "/mnt/users/potato/Ame-Furi/checkpoints"
  save_name: "flower_test1"
  tensorboard_dir: "logs/tensorboard"
  sample_dir: "logs/samples"
  log_interval: 100
  sample_interval: 5
  num_samples: 16

# Distributed training
distributed: true

# Inference (default)
inference:
  output_dir: '/mnt/users/potato/Ame-Furi/outputs'
  num_samples: 1
  class_label: 1