defaults:
  - _self_
  
# Model configuration
model:
  in_channels: 3
  out_channels: 3  # Output same as input for diffusion
  base_channels: 64
  depth: 4
  time_emb_dim: 128

# Diffusion process configuration
diffusion:
  num_timesteps: 1000
  beta_start: 1e-4
  beta_end: 0.02

# Training configuration
training:
  epochs: 30
  batch_size: 16
  seed: 114

# Optimizer configuration
optimizer:
  lr: 1e-4
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0

# Data configuration
data:
  root_dir: "/mnt/users/potato/Ame-Furi/data/5flower"
  image_size: 128
  num_workers: 8

# Logging configuration
logging:
  log_dir: "logs"
  save_dir: "/mnt/users/potato/Ame-Furi/checkpoints"
  tensorboard_dir: "logs/tensorboard"
  sample_dir: "logs/samples"
  log_interval: 100
  sample_interval: 5
  num_samples: 16

# Distributed training
distributed: true